### ISSUE TITLE
Unit Test consume

### ISSUE THREAD

**Issue by sweetat-xfers** [phobos/phobos#125]
I have a simple application which has a phobos based consumer

I have tried to create a simple unit test based on the instructions given:
```ruby
require 'phobos/spec/spec_helper'
require_relative 'myhandler'

describe MyHandler do
  let(:payload) { 'foo' }
  let(:metadata) { Hash(foo: 'bar') }

  it 'consumes my message' do
    expect_any_instance_of(described_class).to receive(:around_consume).with(payload, metadata).once.and_call_original
    expect_any_instance_of(described_class).to receive(:consume).with(payload, metadata).once.and_call_original

    process_message(handler: described_class, payload: payload, metadata: metadata)
  end
end
```

When running 
```
bundle exec rspec myhandler_test.rb
```
The output is:
```
An error occurred while loading ./test/myhandler_tests.rb.
Failure/Error: require 'phobos/spec/spec_helper'

LoadError:
  cannot load such file -- phobos/spec/spec_helper
# ./test/myhandler_tests.rb:1:in `require'
# ./test/myhandler_tests.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00002 seconds (files took 0.11514 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

When I check  the installation directory for phobos, there is no "spec" directory.  Does this mean I should download a copy of spec separately?

How should I perform unit testing of the consume section of the code for this application?

**Comment by dorner** [comment]
@sweetat-xfers looks like the README is wrong. You need to include the test helper like so:
```ruby
require 'phobos/test/helper'

RSpec.configure do |config|
  config.include Phobos::Test::Helper
end
```

Note that you still need to configure Phobos before using the `process_message` method via `Phobos.configure(my_yml_file)`.

**Comment by dorner** [comment]
I've updated the README.

**Comment by petermumford** [comment]
When I try creating a simple unit test I get the below error. I have the same code as above including the updated README.

```
NoMethodError: undefined method `kafka' for nil:NilClass
from .rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/phobos-1.9.0/lib/phobos.rb:70:in `create_kafka_client'
```

**Comment by dorner** [comment]
@petermumford have you configured Phobos yet in your unit test? You need to call `Phobos.configure(path_to_my_config_file)`.
