### ISSUE TITLE
When listeners is getting crashed, it is failing to recover by itself.

### ISSUE THREAD

**Issue by Naren1997** [phobos/phobos#126]
When the Kakfa server is down, the listeners are getting crashed and it is unable to recover by itself, giving be the following error..

> {:message=>"Listener crashed, waiting 19.22s (undefined method `join' for nil:NilClass)", :listener_id=>"438526", :retry_count=>4, :waiting_time=>19.22, :exception_class=>"NoMethodError", :exception_message=>"undefined method `join' for nil:NilClass", :backtrace=>["/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.7.5/lib/kafka/fetcher.rb:66:in `stop'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.7.5/lib/kafka/consumer.rb:113:in `stop"

**Comment by dorner** [comment]
@Naren1997 can you post the full backtrace? These errors seem to be in the underlying RubyKafka library rather than Phobos.

**Comment by Naren1997** [comment]
@dorner Here is the full backtrace, 

> ERROR: {:message=>"Listener crashed, waiting 23.78s (undefined method `join' for nil:NilClass)", :listener_id=>"bcb1bc", :retry_count=>4, :waiting_time=>23.78, :exception_class=>"NoMethodError", :exception_message=>"undefined method `join' for nil:NilClass", :backtrace=>["/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.7.5/lib/kafka/fetcher.rb:66:in `stop'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/ruby-kafka-0.7.5/lib/kafka/consumer.rb:113:in `stop'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/listener.rb:83:in `block in start'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/instrumentation.rb:19:in `block in instrument'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/instrumentation.rb:18:in `instrument'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/listener.rb:80:in `ensure in start'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/listener.rb:80:in `start'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/executor.rb:79:in `run_listener'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/phobos-1.8.0/lib/phobos/executor.rb:45:in `block (2 levels) in start'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'", "/opt/IBM/cobalt/sla.25.4/messenger/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"]}

**Comment by dorner** [comment]
@Naren1997 yeah I can't see anything in Phobos that would cause the fetcher to suddenly lose its thread. Maybe try posting this issue in https://github.com/zendesk/ruby-kafka ?

**Comment by Naren1997** [comment]
@dorner Okay, I'll check in  ruby-kafka. What would be an ideal time interval between listener restarts? Currently I've 10 seconds, will it be due to this?

**Comment by dorner** [comment]
It would totally depend on your broker and consumer settings, and would also depend on why you're crashing in the first place. :)

**Comment by austinmoore** [comment]
We've been having this problem sporadically as well when a kafka broker restarts. I looked into the code of phobos and ruby-kafka and I have a theory of why it occurs. In short, I think the underlying problem is a race condition. I'm just not sure [if ruby-kafka is supporting the threading case](https://github.com/zendesk/ruby-kafka#thread-safety) that phobos is performing.

Here's what I think occurs in this order in these threads:

1. (Thread1) [phobos runner](https://github.com/phobos/phobos/blob/master/lib/phobos/cli/runner.rb#L16) starts the phobos executor
1. (Thread1) [phobos executor](https://github.com/phobos/phobos/blob/master/lib/phobos/executor.rb#L27) iterates over the listeners and uses the thread pool to start each listener in its own thread
1. (Thread2) [phobos executor](https://github.com/phobos/phobos/blob/master/lib/phobos/executor.rb#L31) runs the listener in its own thread via the thread pool
1. (Thread2) [phobos listener](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L166) calls ruby-kafka consume_each_* method
1. (Thread2) [ruby-kafka consumer](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L413) starts the ruby-kafka fetcher
1. (**Thread2**) [ruby-kafka fetcher](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L55) sets `@running = true`. It has **not** initialized `@thread` yet though!
1. (**Thread1**) [phobos executor](https://github.com/phobos/phobos/blob/master/lib/phobos/executor.rb#L43) is given the signal to stop so it iterates over all listeners and tells them to stop. I'm not exactly sure why this occurs in the case of a kafka broken restart, but I'm pretty sure that this or something very similar happens.
1. (Thread1) [phobos listener](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L68) stops the ruby-kafka consumer
1. (Thread1) [ruby-kafka consumer](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L130) stops the ruby-kafka fetcher. **Note: we started the ruby-kafka fetcher in Thread2, but we are stopping it in Thread1.**
1. (Thread1) [ruby-kafka fetcher](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L67) checks that it is `@running`. It is running, but remember that `@thread` has **not** been initialized yet!
1. (**Thread1**) [ruby-kafka fetcher](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L69) attempts to `@thread.join`, but since `@thread` is `nil`, it raises `undefined method 'join' for nil:NilClass`.

I'm not 100% sure this is what is happening, but I think that it is very likely. A "cheap" solution to this problem is for [ruby-kafka fetcher](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L69) to call `@thread&.join` instead of `@thread.join`. Then it won't raise an error if `@thread` is nil. I tried this out in the following monkey patch and it seemed to work. However, I was locally not able to reproduce the race condition without the monkey patch.

```
require 'kafka/fetcher'
module KafkaFetcherExt
  # @see https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L66
  def stop
    return unless @running
    @commands << [:stop, []]
    @thread&.join # Here is the fix. @thread is sometimes, somehow nil.
  end
end
Kafka::Fetcher.prepend(KafkaFetcherExt)
```

https://github.com/zendesk/ruby-kafka#thread-safety

> Furthermore, you should avoid using threads in a consumer unless you're very careful about waiting for all work to complete before returning from the #each_message or #each_batch block.

I'm not sure the "cheap" fix from above is the "correct" fix though. This is why I said, I'm "not sure if ruby-kafka is supporting the threading case that phobos is performing". Is it ok for phobos to start the ruby-kafka fetcher in one thread and stop it in another? In other words, is it ok for the [phobos executor to stop the listeners explicitly](https://github.com/phobos/phobos/blob/master/lib/phobos/executor.rb#L43) or **would it be (thread) safer to send a [signal to the threads to stop](https://ruby-doc.org/core-2.5.0/Thread.html#method-i-kill) which will in turn [stop the listener](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L60) and therefore in turn [stop the ruby-kafka consumer & fetcher](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L113)**.

To implement such a solution I think the following would need to be done:

- Remove the [phobos listener stop](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L63) method (because we assume it is not thread safe).
- Remove the [phobos executor](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L63) call to listener stop and instead kill each thread instead (assuming that killing the thread will still [stop the listener](https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L60)).

**Comment by dorner** [comment]
Hey @austinmoore!

I think you might be misreading the situation in terms of the quote you added from the ruby-kafka docs. That's talking about creating threads within your consumer, which we don't do (we have separate consumers per thread). It also says you shouldn't share a Kafka client between threads, which again we don't do.

I think probably the best solution would be to move the `@running = true` line from *before* the thread is initialized to *after* it's initialized. That would avoid these crashes as I don't think there are any other adverse effects.

**Comment by dorner** [comment]
I do see your point about stopping the listeners from the main thread. I'm not sure what the ramifications are of that, but I can say we've been using Phobos in production for about three years now and have yet to see any real issues coming out of it.

**Comment by reachlin** [comment]
is this problem fixed?

**Comment by dorner** [comment]
I don't think so. I'm not sure if anyone has actually opened an issue on the ruby-kafka library though, as that's where the problem lies.

**Comment by yin-ym** [comment]
I don't agree that this is a pure ruby-kafka issue, I think there should be something we can do here for this retry logic: https://github.com/phobos/phobos/blob/master/lib/phobos/executor.rb#L71 it is keeping using the original listener object for all the way to retry, but if there is any **fundamental issues** in that listener object, it won't be fixed by retry, and the retry is just useless at all. Endless loop with repeating the previous error, just like what is reported here.

**Comment by dorner** [comment]
It's not easy to try and recreate the listener from scratch unfortunately. If you have any ideas or proposals, I'd be happy to review a PR for them.

**Comment by reachlin** [comment]
```
[2021-12-17T00:45:57:708+0000Z] ERROR -- Phobos : <Hash> {:message=>"Listener crashed 
 waiting 61.95s (undefined method `join' for nil:NilClass)" 
 :listener_id=>"586eef" 
 :retry_count=>118 
 :waiting_time=>61.95 
 :exception_class=>"NoMethodError" 
 :exception_message=>"undefined method `join' for nil:NilClass" 
 :backtrace=>["/usr/local/bundle/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:69:in `stop'" 
 "/usr/local/bundle/gems/ruby-kafka-1.3.0/lib/kafka/consumer.rb:130:in `stop'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/listener.rb:113:in `block in stop_listener'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/instrumentation.rb:21:in `block in instrument'" 
 "/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb:180:in `block in instrument'" 
 "/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'" 
 "/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb:180:in `instrument'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/instrumentation.rb:20:in `instrument'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/listener.rb:110:in `stop_listener'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/listener.rb:60:in `ensure in start'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/listener.rb:60:in `start'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/executor.rb:72:in `run_listener'" 
 "/usr/local/bundle/gems/phobos-2.1.0/lib/phobos/executor.rb:31:in `block (2 levels) in start'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'" 
 "/usr/local/bundle/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'" 
 "/usr/local/bundle/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"]}
```

**Comment by reachlin** [comment]
@dorner can we add a retry up limit? because most will run this in a container, if the container stops. the container will be started again. but if phobos keeps this kind of retry failures to itself, the container won't be rebooted.

**Comment by reachlin** [comment]
proposed pr, https://github.com/phobos/phobos/pull/144

**Comment by dorner** [comment]
Hmm... I'm not sure this is the right approach. If one of your listeners crashes, does that mean you have to shut down the entire container? In particular it means that any listeners that are still live won't be able to shut down properly, meaning you're likely to get into a big rebalancing loop for a period of time until you can be stable again.

I am still convinced that the right solution is to fix the underlying ruby-kafka library, and I'm not sure why out of everyone commenting on this thread and suggesting fixes, as far as I can tell no one has attempted to do so. 🤔 From what I can tell we should at least be able to stop the crash by adding a simple null check.

**Comment by reachlin** [comment]
@dorner thanks. how about now? recreate the client when retrying? https://github.com/phobos/phobos/pull/144/files

**Comment by dorner** [comment]
It's a better approach, but it'll take more than recreating the client I think? The consumer was created with the old client and I'm not sure if just changing the reference to a new client will fix anything or break things worse.

**Comment by milosivanovic** [comment]
@reachlin do you know why your PR was closed? Also, were you able to test your fix to see if it was able to handle the retry better?
