### ISSUE TITLE
phobos on ruby 3.1

### ISSUE THREAD

**Issue by sdahlbac** [phobos/phobos#149]
I'm seeing the following error:
```
/Users/me/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:323:in `safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/lib/phobos.rb:117:in `read_configuration'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/lib/phobos.rb:111:in `fetch_configuration'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/lib/phobos.rb:57:in `configure'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/lib/phobos/cli/start.rb:20:in `execute'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/lib/phobos/cli.rb:61:in `start'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/gems/phobos-2.1.0/bin/phobos:10:in `<top (required)>'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/bin/phobos:25:in `load'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/bin/phobos:25:in `<main>'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/sdahlbacka/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
```

As far as I can tell, the issue is that signature for YAML.safe_load has changed between 3.0 and 3.1 from:

`https://ruby-doc.org/stdlib-3.0.0/libdoc/psych/rdoc/Psych.html#method-c-safe_load`

to

`https://ruby-doc.org/stdlib-3.1.0/libdoc/psych/rdoc/Psych.html#method-c-safe_load`

**Comment by dorner** [comment]
Ouchie! Thanks for the heads up. PRs are welcome, not sure if I'll have time to fix in the immediate term.

**Comment by dorner** [comment]
Likely not - earlier Rubies should just interpret the keyword arguments as an option hash and pass it correctly to the method. But we'd have to experiment to make sure.

**Comment by sdahlbac** [comment]
Unfortunately it does not look to be that simple.

I tested with the following diff on 2.5.1

```diff --git a/lib/phobos.rb b/lib/phobos.rb
index 558ca1a..d4694d8 100644
--- a/lib/phobos.rb
+++ b/lib/phobos.rb
@@ -90,9 +90,9 @@ module Phobos
         ERB.new(
           File.read(File.expand_path(configuration))
         ).result,
-        [Symbol],
-        [],
-        true
+        permitted_classes: [Symbol],
+        permitted_symbols: [],
+        aliases: true
       )
     end

All tests fail with:

```
       Failure/Error:
         YAML.safe_load(
           ERB.new(
             File.read(File.expand_path(configuration))
           ).result,
           permitted_classes: [Symbol],
           permitted_symbols: [],
           aliases: true
         )

       ArgumentError:
         unknown keywords: permitted_classes, permitted_symbols, aliases
       # ./lib/phobos.rb:89:in `read_configuration'
       # ./lib/phobos.rb:83:in `fetch_configuration'
       # ./lib/phobos.rb:40:in `configure'
       # ./spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
```

**Comment by dorner** [comment]
Yeah looks like we're going to have to check the version of the Psych gem to get this working correctly.

**Comment by dorner** [comment]
Confirmed that these parameters were added in Psych 3.1.0. So anything older than that will crash. I'll put in a PR to fix this.
